### ISSUE TITLE
Are there any errors in code logic ?

### ISSUE THREAD

**Issue by deku-spider** [emirhanbayar/Fast-Deep-OC-SORT#1]
A smaller α represents a greater similarity in aspect ratio, and why candidates with a smaller α are filtered out.

**Comment by emirhanbayar** [comment]
Thank you for bringing that to my attention. I double-checked the code and the paper. I think that it is correctly implemented in code, but incompletely explained in the paper.

### Regarding code:

```python
    aspect_ratio = bboxes1[..., 2] / bboxes1[..., 3]
    candidates_aspect_ratio = bboxes2[..., 2] / bboxes2[..., 3]
    
    # variable arctan is smaller if similarity is high
    arctan = np.arctan(aspect_ratio) - np.arctan(candidates_aspect_ratio)
    
    # variable v is bigger if arctan is smaller and similarity is high
    v = 1 - ((4 / np.pi ** 2) * arctan ** 2)

    # scale down the v if iou is smaller
    alpha = v / (1 - iou + v)
  ```

Everything seemed correct to me. What do you think?

### Regarding paper:
 
 In the paper this logic is explained as:
 
$$
    V = \frac{4}{\pi^2} \cdot (\arctan\left(\frac{w_1}{h_1}\right) - \arctan\left(\frac{w_2}{h_2}\right))^2
$$

$$
  \alpha = \frac{V}{(1 - IoU) + V}
$$
  
I think the calculation of V must be corrected as 

$$
    V =1 -  \frac{4}{\pi^2} \cdot (\arctan\left(\frac{w_1}{h_1}\right) - \arctan\left(\frac{w_2}{h_2}\right))^2
$$

**Comment by deku-spider** [comment]
Thanks for your answer.
